name: OnMain
on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
jobs:
  OnMain:
    name: OnMain
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Golang
        run: ./bin/install-go.sh
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          registry-url: 'https://registry.npmjs.org'
      - name: Check
        run: yarn test
      - name: Run node
        run: yarn install && yarn start
      - name: Run go
        run: yarn start:go
      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          # if head commit is release
          if [[ `git log -1 --pretty=%B` == release* ]]; then
            echo "starting release..."
            git tag $new_version
            git push origin $new_version

            npm publish ./build
          else
            echo "starting prerelease..."
            previous_version=`git describe --tags --abbrev=0`
            echo "previous_version: ${previous_version}"
            new_version=`./node_modules/.bin/semver $previous_version --increment prerelease --preid beta`
            echo "new_version: ${new_version}"

            # do I actually need to do this?
            cd build
            npm version $new_version --commit-hooks false --git-tag-version false
            cat package.json
            cd ..

            git tag $new_version
            git push origin $new_version

            npm publish ./build
          fi


