name: OnMain
on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
jobs:
  OnMain:
    name: OnMain
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Golang
        run: ./bin/install-go.sh
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - name: Check
        run: yarn test
      - name: Run node
        run: yarn install && yarn start
      - name: Run go
        run: yarn go:start
      - name: Publish
        run: |
          # if head commit is release
          if [[ `git log -1 --pretty=%B` == release* ]]; then
            echo "starting release..."
          else
            echo "starting prerelease..."
            previous_version=`git describe --tags --abbrev=0`
            echo $previous_version
            new_version=`./node_modules/.bin/semver $previous_version --increment prerelease --preid beta`
            echo $new_version
            npm version $new_version --commit-hooks false --git-tag-version false
            ls -l
            # npm publish ./build
          fi


