name: Prepare
on:
  workflow_dispatch:
jobs:
  Create_Release_Commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Golang
        run: ./bin/install-go.sh

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          registry-url: 'https://registry.npmjs.org'

      - name: git_user
        run: |
          git config --global user.name 'goatlang'
          git config --global user.email 'goatlang@users.noreply.github.com'

      - name: Check
        run: |
          yarn install
          yarn build
          yarn test
          yarn start

      - name: Determine next version
        id: determine_next_version
        run: |
          git commit --allow-empty -m 'release: '
          NEW_VERSION=`./bin/gotagger`
          git reset HEAD~
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT

      - name: changelog
        env:
          NEW_VERSION: ${{ steps.determine_next_version.outputs.NEW_VERSION }}
        run: |
          yarn changelog $NEW_VERSION

      - name: PR
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: >-
            release: ${{ steps.determine_next_version.outputs.NEW_VERSION }}
          title: >-
            release: ${{ steps.determine_next_version.outputs.NEW_VERSION }}

