name: Prepare
on:
  workflow_dispatch:
jobs:
  Create_Release_Commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          registry-url: 'https://registry.npmjs.org'

      - name: git_user
        run: |
          git config --global user.name 'goatlang'
          git config --global user.email 'goatlang@users.noreply.github.com'

      - name: Check
        run: |
          yarn install
          yarn build
          yarn test:node
          yarn start:node

      - name: Version info
        run: node ./bin/version.js --pretty --release

      - name: Determine next version
        id: determine_next_version
        run: |
          NEW_VERSION=`node ./bin/version.js --value="nextVersion" --release`
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT

      - name: Changelog
        if: ${{ steps.determine_next_version.outputs.NEW_VERSION != 'null' }}
        run: yarn changelog

      - name: Generate commit message
        id: commit_message
        env:
          NEW_VERSION: ${{ steps.determine_next_version.outputs.NEW_VERSION }}
        if: ${{ steps.determine_next_version.outputs.NEW_VERSION != 'null' }}
        run: |
          COMMIT_MESSAGE="release: ${NEW_VERSION}"
          echo "COMMIT_MESSAGE=$COMMIT_MESSAGE" >> $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT

      - name: PR
        uses: peter-evans/create-pull-request@v5
        if: ${{ steps.determine_next_version.outputs.NEW_VERSION != 'null' }}
        with:
          commit-message: ${{ steps.commit_message.outputs.COMMIT_MESSAGE }}
          title: ${{ steps.commit_message.outputs.COMMIT_MESSAGE }}

