name: Release
on:
  workflow_dispatch:
jobs:
  Release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Golang
        run: ./bin/install-go.sh
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          registry-url: 'https://registry.npmjs.org'
      - name: Check
        run: yarn install && yarn test
      - name: Run node
        run: yarn install && yarn start
      - name: Run go
        run: yarn start:go
      - name: release
        id: release
        run: |
          git config --global user.name 'goatlang'
          git config --global user.email 'goatlang@users.noreply.github.com'

          yarn changelog

          new_version=`./bin/gotagger`
          branch_name="release-${new_version}"

          echo "NEW_VERSION=$new_version" >> $GITHUB_OUTPUT
          echo "BRANCH_NAME=$branch_name" >> $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT
      - name: PR
        env:
          NEW_VERSION: ${{ steps.release.outputs.NEW_VERSION }}
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: >-
            release: ${{ steps.release.outputs.NEW_VERSION }}
          title: >-
            release: ${{ steps.release.outputs.NEW_VERSION }}
          branch: ${{ steps.release.outputs.BRANCH_NAME }}

