name: Release
on:
  workflow_dispatch:
jobs:
  Release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Golang
        run: ./bin/install-go.sh
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - name: Check
        run: yarn test
      - name: Run node
        run: yarn install && yarn start
      - name: Run go
        run: yarn start:go
      - name: release
        run: |
          git config --global user.name 'goatlang'
          git config --global user.email 'goatlang@users.noreply.github.com'

          yarn changelog
          git add CHANGELOG.md

          NEXT_VERSION=`./bin/gotagger`
          git commit --allow-empty -m "release: $NEXT_VERSION"

          # ./bin/gotagger -release -push
      - name: PR
        uses: peter-evans/create-pull-request@v5

