name: Release
on:
  workflow_dispatch:
jobs:
  Release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - name: Install Golang
        run: |
          curl -OL https://golang.org/dl/go1.16.7.linux-amd64.tar.gz
          sudo tar -C /usr/local -xvf go1.16.7.linux-amd64.tar.gz
          export PATH=/usr/local/go/bin:$PATH
          go version
      - name: Install gotagger
        run: |
          ./bin/gotagger --version
      - name: go:start
        run: yarn go:start
      - name: go:version
        run: yarn go:version
      - name: Run Node
        run: |
          yarn install
          yarn start
      - name: gotagger
        run: |
          git config --global user.name 'jonbri'
          git config --global user.email 'jonbri@users.noreply.github.com'
          yarn run go:release
      - name: PR
        uses: peter-evans/create-pull-request@v5

