name: Release
on:
  workflow_dispatch:
jobs:
  Release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Golang
        run: ./bin/install-go.sh
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - name: Check
        run: yarn test
      - name: Run node
        run: yarn install && yarn start
      - name: Run go
        run: yarn start:go
      - name: release
        run: |
          git config --global user.name 'goatlang'
          git config --global user.email 'goatlang@users.noreply.github.com'

          cat package.json

          new_version=`./bin/gotagger`
          echo "new_version: ${new_version}";
          cat package.json

          npm version $new_version --commit-hooks false --git-tag-version false

          yarn changelog
          git add CHANGELOG.md

          git commit --allow-empty -m "release: $new_version"
      - name: PR
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "release: ${new_version}"

