name: Review
on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
jobs:
  Review:
    name: Review
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - name: Install Golang
        run: |
          curl -OL https://golang.org/dl/go1.16.7.linux-amd64.tar.gz --output-dir /tmp
          sudo tar -C /usr/local -xvf /tmp/go1.16.7.linux-amd64.tar.gz
          export PATH=/usr/local/go/bin:$PATH
          go version
      - name: Install gotagger
        run: |
          ./bin/gotagger --version
      - name: go:start
        run: yarn go:start
      - name: go:version
        run: yarn go:version
      - name: Run Node
        run: |
          yarn install
          yarn start

