name: Review
on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
jobs:
  Review:
    name: Review
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Golang
        run: ./bin/install-go.sh
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - name: Check
        run: yarn test
      - name: Run node
        run: yarn install && yarn start
      - name: Run go
        run: yarn go:start

